### ISSUE TITLE
Use /proc/self/stat on Linux

### ISSUE THREAD

**Issue by Freaky** [jhpratt/num-threads#1]
Instead of walking every entry in `/proc/self/task`, would it not be better to read `/proc/self/stat` and parse field 20?  [proc(5)](https://man7.org/linux/man-pages/man5/proc.5.html):

              (20) num_threads  %ld
                     Number of threads in this process (since Linux
                     2.6).  Before kernel 2.6, this field was hard coded
                     to 0 as a placeholder for an earlier removed field.

**Comment by jhpratt** [comment]
Yeah, this would be preferable.
