### ISSUE TITLE
tests fail with Rust 1.67.0+

### ISSUE THREAD

**Issue by decathorpe** [jhpratt/num-threads#13]
I'm maintaining the package for the num_threads crate in Fedora Linux, and i noticed that builds of the crate started to fail with Rust 1.67.0 due to failing tests:

```
     Running `/builddir/build/BUILD/num_threads-0.1.6/target/release/deps/num_threads-03ca46149c224543 --test-threads 1`
running 2 tests
test test::is_single_threaded ... FAILED
test test::num_threads ... FAILED
failures:
---- test::is_single_threaded stdout ----
thread 'test::is_single_threaded' panicked at 'assertion failed: `(left == right)`
  left: `Some(false)`,
 right: `Some(true)`', src/lib.rs:56:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
---- test::num_threads stdout ----
thread 'test::num_threads' panicked at 'assertion failed: `(left == right)`
  left: `Some(2)`,
 right: `Some(1)`', src/lib.rs:44:13
failures:
    test::is_single_threaded
    test::num_threads
test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
error: test failed, to rerun pass `--lib`
```

Is it possible that Rust 1.67.0 changed the way test runners work? It looks like there's one too much thread even when using `-- --test-threads 1`.

**Comment by Freaky** [comment]
[libtest: run all tests in their own thread, if supported by the host](https://github.com/rust-lang/rust/commit/3af058ec947b91590fe3ffd47a9bb2d690d2cb9d).

This has always been fragile and hacky.  A proper fix would be to compile a standalone test program and test it executes as expected, instead of assuming anything about how the test harness works.

**Comment by jhpratt** [comment]
It's definitely that commit that changed things. I don't see any problems with a workaround and would accept a pull request to that effect.

**Comment by Freaky** [comment]
My reworked tests pass on FreeBSD.  They are more aggressive about spinning threads up and down - I wonder if Linux is showing some slight raciness in its reported thread count?

**Comment by jhpratt** [comment]
I was _just_ working on a fix to this. Basically I'm going to avoid the test harness altogether using `Cargo.toml`'s `harness = false`. Give me ~10 minutes and a PR will be open.
